# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Metz
description: > # this means to ignore newlines until "baseurl:"
  An experiment in writing and documenting 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.nicmetz.com/" # the base hostname & protocol for your site
twitter_username: crsoystr
github_username:  crsoystr

# Build settings
markdown: kramdown
